### ISSUE TITLE
1.4.2 已更新啦

### ISSUE THREAD

**Issue by congbo** [shingwasix/BaiduPush-iOS-SDK#2]
http://push.baidu.com/sdk/push_client_sdk_for_ios

**Comment by shingwasix** [comment]
谢谢提醒，现在升级了OSX10.11，暂时更新不了。

**Comment by shingwasix** [comment]
已更新shingwasix/BaiduPush-iOS-SDK@8e6eac01cba378c9b4994d96495a439fe0094385
